name: Local Sonatype Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B --file pom.xml package dependency:copy-dependencies

      - name: Run Evaluate Action
        id: evaluate
        uses: sonatype/actions/evaluate@v1.3.0
        with:
          iq-server-url: http://localhost:8070/iq-server.com/ 
          username: ${{ secrets.LOCAL_USR }}
          password: ${{ secrets.LOCAL_PSCD }}
          application-id: JavaTestApp
          scan-targets: '**/*.jar'
          sarif-file: 'sariffile.sarif'
          upload-sarif-file: 'true'
          enable-callflow: true 
